### ISSUE TITLE
Warn Js Controller Version 4.0.0 Alpha

### ISSUE THREAD

**Issue by sigi2345** [jack-blackson/ioBroker.meteoalarm#100]
Hallo, habe den neuen Js Controller Version 4.0.0 Alpha installiert, seit dem kommt das:

`<html>
<body>

host.MedionHome) | 2022-02-02 09:15:12.469 | info | host.Medion(Home) instance system.adapter.meteoalarm.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
meteoalarm.0 | 2022-02-02 09:15:11.920 | info | Terminated (NO_ERROR): Without reason
meteoalarm.0 | 2022-02-02 09:15:11.919 | info | Updated Weather Alarms for Oberösterreich -> 2 warning(s) found
meteoalarm.0 | 2022-02-02 09:15:03.403 | info | starting. Version 2.0.10 (non-npm: jack-blackson/ioBroker.meteoalarm#9a9d202fc1b30f20f0b6121bae0a5b8a9afb83ee) in C:/Program Files/iobroker/Home/node_modules/iobroker.meteoalarm, node: v14.18.3, js-controller: 4.0.0-alpha.67-20220131-6621d47f
meteoalarm.0 | 2022-02-02 09:15:01.967 | warn | This object will not be created in future versions. Please report this to the developer.
meteoalarm.0 | 2022-02-02 09:15:01.967 | warn | Object meteoalarm.0.level is invalid: Default value has to be type "number" but received type "string"
meteoalarm.0 | 2022-02-02 09:15:01.960 | warn | This object will not be created in future versions. Please report this to the developer.
meteoalarm.0 | 2022-02-02 09:15:01.959 | warn | Object meteoalarm.0.noOfAlarms is invalid: Default value has to be type "number" but received type "string"

</body>
</html>`

Plattform: Windows
RAM: 16 GB 
NODE.JS: V14.18.3
NPM: 6.14.15
JS Controller: 4.0.0
Admin: 5.2.3
Web: 4.1.1
Socket.io: 4.1.0

**Comment by jack-blackson** [comment]
@sigi2345  Danke für die Info. Ich hab es mir grad im Forum angesehen, warte noch auf die Beta Version, die ja Richtung Wochennde kommen sollte, und kontrolliere es dann. Noch ist es mir nicht ganz klar, da ich hier eigentlich schon Number-Werte überall schreibe.

**Comment by sigi2345** [comment]
> @sigi2345 Danke für die Info. Ich hab es mir grad im Forum angesehen, warte noch auf die Beta Version, die ja Richtung Wochennde kommen sollte, und kontrolliere es dann. Noch ist es mir nicht ganz klar, da ich hier eigentlich schon Number-Werte überall schreibe.

Habe mal alle Objekte gelöscht, jetzt kommt das bei Ausführung des Crons:

`<html>
<body>


host.Medion(Home) | 2022-02-03 08:00:14.275 | error | instance system.adapter.meteoalarm.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.Medion(Home) | 2022-02-03 08:00:10.591 | error | instance system.adapter.meteoalarm.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.Medion(Home) | 2022-02-03 08:00:06.531 | error | instance system.adapter.meteoalarm.2 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.Medion(Home) | 2022-02-03 08:00:02.746 | error | instance system.adapter.meteoalarm.3 terminated with code 6 (UNCAUGHT_EXCEPTION)


</body>
</html>`

**Comment by sigi2345** [comment]
`<html>
<body>


meteoalarm.0 | 2022-02-03 08:05:02.168 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
meteoalarm.0 | 2022-02-03 08:05:02.167 | debug | Plugin sentry destroyed
meteoalarm.0 | 2022-02-03 08:05:02.166 | error | Cannot read property 'warn' of undefined
meteoalarm.0 | 2022-02-03 08:05:02.166 | error | TypeError: Cannot read property 'warn' of undefined at setObjectWithDefaultValue (C:\Program Files\iobroker\Home\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:1650:26) at Adapter.setForeignObject (C:\Program Files\iobroker\Home\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:2148:13) at Adapter.extendForeignObject (C:\Program Files\iobroker\Home\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:2271:33)
meteoalarm.0 | 2022-02-03 08:05:02.164 | error | unhandled promise rejection: Cannot read property 'warn' of undefined
meteoalarm.0 | 2022-02-03 08:05:02.164 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
meteoalarm.0 | 2022-02-03 08:05:02.162 | warn | This object will not be created in future versions. Please report this to the developer.
meteoalarm.0 | 2022-02-03 08:05:02.162 | warn | Object meteoalarm.0.noOfAlarms is invalid: Default value has to be type "number" but received type "string"
meteoalarm.0 | 2022-02-03 08:05:02.091 | debug | States connected to redis: 127.0.0.1:9010
meteoalarm.0 | 2022-02-03 08:05:02.052 | debug | States create User PubSub Client
meteoalarm.0 | 2022-02-03 08:05:02.051 | debug | States create System PubSub Client
meteoalarm.0 | 2022-02-03 08:05:02.032 | debug | Redis States: Use Redis connection: 127.0.0.1:9010
meteoalarm.0 | 2022-02-03 08:05:01.999 | debug | Objects connected to redis: 127.0.0.1:9011
meteoalarm.0 | 2022-02-03 08:05:01.994 | debug | Objects client initialize lua scripts
meteoalarm.0 | 2022-02-03 08:05:01.905 | debug | Objects create User PubSub Client
meteoalarm.0 | 2022-02-03 08:05:01.905 | debug | Objects create System PubSub Client
meteoalarm.0 | 2022-02-03 08:05:01.904 | debug | Objects client ready ... initialize now
meteoalarm.0 | 2022-02-03 08:05:01.872 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9011
meteoalarm.0 | 2022-02-03 08:00:13.694 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
meteoalarm.0 | 2022-02-03 08:00:13.692 | error | Cannot read property 'warn' of undefined
meteoalarm.0 | 2022-02-03 08:00:13.692 | error | TypeError: Cannot read property 'warn' of undefined at setObjectWithDefaultValue (C:\Program Files\iobroker\Home\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:1650:26) at Adapter.setForeignObject (C:\Program Files\iobroker\Home\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:2148:13) at Adapter.extendForeignObject (C:\Program Files\iobroker\Home\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:2271:33)
meteoalarm.0 | 2022-02-03 08:00:13.690 | error | unhandled promise rejection: Cannot read property 'warn' of undefined
meteoalarm.0 | 2022-02-03 08:00:13.690 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
meteoalarm.0 | 2022-02-03 08:00:13.688 | warn | This object will not be created in future versions. Please report this to the developer.
meteoalarm.0 | 2022-02-03 08:00:13.687 | warn | Object meteoalarm.0.noOfAlarms is invalid: Default value has to be type "number" but received type "string"


</body>
</html>`

**Comment by jack-blackson** [comment]
@sigi2345  Problem sollte mit V2.1.1 gelöst sein, sollte in wenigen Minuten im Latest sein.
