### ISSUE TITLE
Terminated (UNCAUGHT_EXCEPTION): Without reason

### ISSUE THREAD

**Issue by vaaarg** [jack-blackson/ioBroker.meteoalarm#116]
Neuinstallation des Adapters hat nichts bewirkt.
Bekomme den Fehler seit ca 2 Tagen. Hatte ein Node Update von 12 auf 14 durchgeführt.
Alle anderen Adapter haben das aber problemlos verkraftet. Ob der Fehler tatsächlich daher kommt mag ich nicht zu beurteilen

Installierte Version: 2.1.1

`pio4gb
Plattform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.75 GB
System-Betriebszeit
3 T. 00:36:35
Node.js
v14.19.2
time
1652608634970
timeOffset
-120
Anzahl der Adapter
490
NPM
6.14.17
Datenträgergröße
58.29 GB
freier Festplattenspeicher
51.26 GB
Betriebszeit
3 T. 00:36:28
Aktive Instanzen
19
Weg
/opt/iobroker/
Hostname
pio4gb`

`<html>
<body>

host.pio4gb | 2022-05-15 11:40:04.302 | error | instance system.adapter.meteoalarm.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
meteoalarm.0 | 2022-05-15 11:40:03.765 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
meteoalarm.0 | 2022-05-15 11:40:03.763 | info | terminating
meteoalarm.0 | 2022-05-15 11:40:03.713 | error | Cannot read property 'valueName' of undefined
meteoalarm.0 | 2022-05-15 11:40:03.712 | error | TypeError: Cannot read property 'valueName' of undefined at /opt/iobroker/node_modules/iobroker.meteoalarm/main.js:429:69 at Array.forEach (<anonymous>) at checkRelevante (/opt/iobroker/node_modules/iobroker.meteoalarm/main.js:411:11) at /opt/iobroker/node_modules/iobroker.meteoalarm/main.js:176:33 at Parser.<anonymous> (/opt/iobroker/node_modules/xml2js/lib/parser.js:304:18) at Parser.emit (events.js:400:28) at Parser.emit (domain.js:475:12) at SAXParser.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:262:26) at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35) at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)
meteoalarm.0 | 2022-05-15 11:40:03.696 | error | unhandled promise rejection: Cannot read property 'valueName' of undefined
meteoalarm.0 | 2022-05-15 11:40:03.695 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

**Comment by jack-blackson** [comment]
I moved it in the meantime to the latest/beta release, so you should be able to access it directly in admin. But I think the error is not happening even before you update - seems to be an issue with the german xml files yesterday, but probably you can check.

**Comment by vaaarg** [comment]
> but probably you can check.

Thank you errors gone
