### ISSUE TITLE
instance system.adapter.meteoalarm.0 already running with pid 625975

### ISSUE THREAD

**Issue by SurfGargano** [jack-blackson/ioBroker.meteoalarm#138]
Seit einem der letzten Updates vom Admin kommt diese Warnung regelmässig alle 10 Minuten im Cron Takt.
Ich habe direkt Netzwerk Verbindung mit Kabel, also kein WLAN.

**Comment by jack-blackson** [comment]
Welche Version von Admin und des Adapters hast du?

**Comment by SurfGargano** [comment]
Admin 6.2.20, Meteoalarrm 2.2.1

**Comment by jack-blackson** [comment]
Kommt es nach einem Neustart von ioBroker sofort wieder?

**Comment by SurfGargano** [comment]
Seit dem Iobroker Restart ist Ruhe bis jetzt.

**Comment by jack-blackson** [comment]
Servus! Ist es nochmals passiert? Sonst würde ich vorschlagen, dass wir dieses Issue schließen.

**Comment by SurfGargano** [comment]
Seit dem Restart ist Ruhe. Du kannst den Issue schließen.
