### ISSUE TITLE
What you do with "No geocode included" entry messages?

### ISSUE THREAD

**Issue by Apollon77** [jack-blackson/ioBroker.meteoalarm#141]
https://github.com/jack-blackson/ioBroker.meteoalarm/blob/master/main.js#L701

This produced 91k messages on 77 users in the last 90 days ... Please do something with it or remove it from Sentry reporting :-)

**Comment by jack-blackson** [comment]
This was a temporary logging, to see when this happens - normally every alarm should include a geocode, but it seems that this is not the case. I will keep my error handling, but stop logging it when releasing the next version to latest.

**Comment by Apollon77** [comment]
Cool ... thank you! We can also blacklist versions in sentry to be ignored completely (if you have such "spammer things"

**Comment by jack-blackson** [comment]
I just published the 2.3.1 to latest, that is not doing this breadcrumb any more. But of course we can also blacklist the versions that create the issues. I think, if we blacklist 2.2.1, 2.2.0 and 2.1.5, most of it should be gone.

**Comment by Apollon77** [comment]
done, thx!
