### ISSUE TITLE
alarms objects are not removed when the alarm no longer exists

### ISSUE THREAD

**Issue by SurfGargano** [jack-blackson/ioBroker.meteoalarm#147]
With the new version  2.3.1 the alarm ids are very. very long named.
e.g meteoalarm.0.alarms.249002760DWDPVW1670313180000f86072ed-7697-46e6-a7e9-b4c7ea8b2eeaMUL

These objects are not removed completely when the alarm no longer exists, so the number of objects is growing.
It exists still 
`meteoalarm.0.alarms.249002760DWDPVW1670313180000f86072ed-7697-46e6-a7e9-b4c7ea8b2eeaMUL.updateIdentifier`

Until the version 2.2.1 the object ids are numbered with alarm_0, alarm_1 ..., so it is easier to walk thru the alarm objects.
Now it is impossible.

Furthermore with version 2.2.1 the alarm objecs are removed completely , when the alarm no longer exists

**Comment by jack-blackson** [comment]
Hello @SurfGargano !

Yes, there was a change in the name. The reason was that I am better able to track new alarms, and also changed alarms, to make it easier to e.g. send out the notifications for new alarms, and other stuff. The naming before was not that good idea, as it could happen that one alarm changes its name during his life, when e.g. some other alarms are added, so changes had not been able to track.

In general, my intention was that it is not necessary for the users to think about the name of these objects, and better use either the JSON object, or the notification objects, or even the HTML widget. Where is your problem with the name coming from here?

That alarms are not deleted is of course not the way it should work. Could you please set the adapter for one run to debug and post the log of one run?

**Comment by SurfGargano** [comment]
Here are the logs: 
[MeteoAlarmExistsJSON.txt](https://github.com/jack-blackson/ioBroker.meteoalarm/files/10183930/MeteoAlarmExistsJSON.txt)
[MeteoNoAlamJSON.txt](https://github.com/jack-blackson/ioBroker.meteoalarm/files/10183932/MeteoNoAlamJSON.txt)

Furthermore  now a following situation:
An event was existing. A restart of iobroker occured due a line powerfail.
After starting iobroker the event in JSON is empty, but the old alarm still exists.
I suggest, if no event exists, delete all alarms.

**Comment by jack-blackson** [comment]
@SurfGargano The logic is like this: first I get all active alarms from meteoalarm. Then i create/update the objects. In the end, I compare the data from meteoalarm with the existing objects, and this should then lead to the result that obsolete alarms will be deleted.

What I can see in the log is that there is at the moment one alarm that can not be deleted:

`2022-12-08 10:00:05.833 - warn: meteoalarm.0 (10041) redis del meteoalarm.0.alarms.249002760DWDPVW1670412780000d3874d4d-d9f4-44c6-ae05-5560c8eabd99MUL.icon, error - Cannot read properties of null (reading 'del')
2022-12-08 10:00:05.838 - warn: meteoalarm.0 (10041) Could not remove state of meteoalarm.0.alarms.249002760DWDPVW1670412780000d3874d4d-d9f4-44c6-ae05-5560c8eabd99MUL.icon: Cannot read properties of null (reading 'del')`

Is this the only alarm in there at the moment? can you show me how this object tree looks like ( a screenshot)? especially the "icon" state. 

The "Alarm Exists" looks good, just this deletion error is really strange.

**Comment by SurfGargano** [comment]
This is the ghost alarm
![image](https://user-images.githubusercontent.com/70272783/206474114-07899dff-4276-44ed-aa3c-e779c5fecbe0.png)

**Comment by jack-blackson** [comment]
Thanks for all the details - it seems that the timing of the deletion is not 100% good - the adapter is not waiting till everything is deleted. I will try to find a solution for that and will let you know when I have something ready.

**Comment by SurfGargano** [comment]
Thanks, can you please add the alarm type in JSON acccording to the alarm table in the description.

**Comment by jack-blackson** [comment]
Hey! I added a fix. Can you please try to install the new version 2.3.2 with this link and let me know if you still have this issue?
https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.32. Regarding the Alarm Type: I guess you want the text, not the integer, right?

**Comment by SurfGargano** [comment]
I am not sure installing the v2.32 correctly. I have installed via adapter / own path
![image](https://user-images.githubusercontent.com/70272783/210094043-11d583bc-35c9-4514-bce6-fa145fab5cf5.png)
Is this correct ?
The instance show me still the version 2.3.1.

**Comment by jack-blackson** [comment]
This looks correct..can you please show me the log when you run the installation ?

**Comment by SurfGargano** [comment]
I have a second time imstalles and an error is shown:

$ iobroker url https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.32 --host raspberrypi --debug

install jack-blackson/ioBroker.meteoalarm#v2.32

NPM version: 8.15.0

Installing jack-blackson/ioBroker.meteoalarm#v2.32... (System call)

npm ERR! code 1

npm ERR! command git --no-replace-objects checkout v2.32npm ERR! error: pathspec 'v2.32' did not match any file(s) known to git

npm ERR! A complete log of this run can be found in:

npm ERR! /home/iobroker/.npm/_logs/2022-12-31T09_06_16_732Z-debug-0.log

upload [38] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/geocodes.json geocodes.json application/json

upload [30] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/i18n/pt/translations.json i18n/pt/translations.json application/json

upload [20] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/black/t5.png icons/black/t5.png image/png

upload [19] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/black/t6.png icons/black/t6.png image/png

upload [18] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/black/t7.png icons/black/t7.png image/png

upload [17] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/black/t8.png icons/black/t8.png image/png

upload [16] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/black/t9.png icons/black/t9.png image/png

upload [15] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t1.png icons/white/t1.png image/png

upload [14] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t10.png icons/white/t10.png image/png

upload [13] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t12.png icons/white/t12.png image/png

upload [12] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t13.png icons/white/t13.png image/png

upload [11] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t2.png icons/white/t2.png image/png

upload [10] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t3.png icons/white/t3.png image/png

upload [9] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t4.png icons/white/t4.png image/png

upload [8] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t5.png icons/white/t5.png image/png

upload [7] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t6.png icons/white/t6.png image/png

upload [6] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t7.png icons/white/t7.png image/png

upload [5] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t8.png icons/white/t8.png image/png

upload [4] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/icons/white/t9.png icons/white/t9.png image/png

upload [3] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/index_m.html index_m.html text/html

upload [2] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/meteoalarm.png meteoalarm.png image/png

upload [1] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/screenshot.png screenshot.png image/png

upload [0] meteoalarm.admin /opt/iobroker/node_modules/iobroker.meteoalarm/admin/words.js words.js application/javascript

Process exited with code 0

**Comment by jack-blackson** [comment]
@SurfGargano Sorry, there was a typo in the link :( it is https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.3.2

**Comment by SurfGargano** [comment]
Install was ok now. Waiting for the next alarm,

Happy new year !
Werner

**Comment by jack-blackson** [comment]
I hope it is working fine now. 

Happy new year,
Alex

**Comment by SurfGargano** [comment]
Hi Alex,
The new version 2.3.2 works now as expected.
best regards
Werner
