### ISSUE TITLE
Pushover shipping across all instances

### ISSUE THREAD

**Issue by Draexl** [jack-blackson/ioBroker.meteoalarm#149]
I use three pushover instances. In the settings I have set that the pushover.1 should be sent. In the event of an alarm, however, I still receive a message from each instance. Is this known?

**Comment by Draexl** [comment]
Log:
Error from Pushover: SyntaxError: Unexpected token < in JSON at position 0

**Comment by jack-blackson** [comment]
Hey! I found the problem and fixed it in 2.3.2. This version should be available in the latest/beta branch in a few hours. Please give it a try and let me know if it works fine for you now.

**Comment by Draexl** [comment]
It works. Thanks :-)
