### ISSUE TITLE
adapter stop itself

### ISSUE THREAD

**Issue by Ilovegym66** [jack-blackson/ioBroker.meteoalarm#16]
With Admin 3.6.5, js-controller 1.5.14, and Meteoalarm 1.05 ( and older versions, too) the adapter stop itself:
`
host.iobroker | 2019-09-25 11:02:18.842 | error | instance  system.adapter.meteoalarm.0 terminated by request of the instance  itself and will not be restarted, before user restarts it.
-- | -- | -- | --
`

**Comment by jack-blackson** [comment]
@Ilovegym66  Sorry, I missed those issues. Do you still have this issue in the last versions?

**Comment by jack-blackson** [comment]
Should be solved with the current versions - please reopen if still happening
