### ISSUE TITLE
Please check and fix the sentry reported issues!!

### ISSUE THREAD

**Issue by Apollon77** [jack-blackson/ioBroker.meteoalarm#163]
https://sentry.iobroker.net/organizations/iobroker/issues/?project=124&statsPeriod=90d

**Comment by jack-blackson** [comment]
I already found the problem for the issue that creates the most pin and released  new version 2.3.4 - seems that there is an incomplete xml published by the austrian weather team that creates the trouble

**Comment by Apollon77** [comment]
Ok cool, if I coshould exclude (older) versions from sentry  then tell me the version ranges
