### ISSUE TITLE
Alle 10 min Warning adapter already started

### ISSUE THREAD

**Issue by SurfGargano** [jack-blackson/ioBroker.meteoalarm#167]
**Describe the bug**  
Da ein Cron verwendet wird, wird die Instanz alle 10 min neu gestartet. Da der Prozess vorher nicht gelöscht wurde, gibt es jedesmal eine Warnung.
Das System nimmt zum Glück den gleichen PID, gibt aber eine Warnung aus.

**To Reproduce**  
Einfach laufen lassen

**Expected behavior**  
Prozess sollte nach Durchlauf des Programms beendet werden. (Das machen andere Adapter auch)
Oder kein Cron verwenden sondern schedule oder interval.

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: <2.3.5>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by jack-blackson** [comment]
Hallo!

Normalerweise sollte sich der Adapter sauber beenden, nach jedem Lauf. Könntest du mir bitte den Adapter auf Debug stellen, und das Protokoll eines Durchlaufs posten?

**Comment by SurfGargano** [comment]
Da war irgend etwas nicht sauber, da kamen gar keine Meldungen im Debug Modus. Ich habe den Adapter neu installiert, jetzt geht es wie es soll, auch das Schließen.
Danke
