### ISSUE TITLE
"Keine Warnungen" senden funktioniert nicht

### ISSUE THREAD

**Issue by neunteufels** [jack-blackson/ioBroker.meteoalarm#169]
Mir ist gerade auf gefallen, dass keine Benachrichtigung via Telegram kommt, wenn keine Warnungen mehr anstehen.
Das hat doch schon mal funktioniert, oder?

"Keine Warnungen" senden ist angehakt.

Was kann ich machen damit ich die wieder bekomme?

Version: 2.3.5
2 Instanzen
meteoalarm.0 = Österreich / Gmünd
meteoalarm.1 = Österreich / Freistadt
Alle Alarmtypen ausgewählt
Stil der Warnstufe mit !!!
Telegram auf telegram.1

Falls mehr Infos benötigt werden, dann bitte um Info.

**Comment by jack-blackson** [comment]
Hier hat sich mit der letzten Version leider ein kleiner Fehler eingeschlichen.  Ich hab das Problem gefunden, und grad eine neue Version im Latest freigegeben - sollte in wenigen MInuten bereit sein, die 2.3.6. Bitte gib mir kurz Bescheid, ob es jetzt wieder funktioniert.

**Comment by neunteufels** [comment]
Version 2.3.6 läuft in zwei Instanzen und ich werde es beobachten.
Danke!
