### ISSUE TITLE
Seems alarm for Switzerland no longer working since a while

### ISSUE THREAD

**Issue by memberxx** [jack-blackson/ioBroker.meteoalarm#180]
Log info:

2.1: Atom URL https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-switzerland not available - error Error: socket hang up

**Comment by memberxx** [comment]
> Hello!
> 
> Do you get this error message constantly? Have you tried to restart iobroker? What location in switzerland are you using?
> 
> Please also add the adapter version!

I restarted the Meteoalarm instance, used several ones, last where it should have a warning right now region Goldau

**Comment by jack-blackson** [comment]
I will keep an eye on that, but I could not see a warning this point of time on https://meteoalarm.org/ - this is where I get the data from. So it would be good to please check next time when you think there should be a warning if you could see it on meteoalarm.org<http://meteoalarm.org/>, and let me then know.

Thanks!

Am 16.11.2023 um 14:15 schrieb memberxx ***@***.***>:



Hello!

Do you get this error message constantly? Have you tried to restart iobroker? What location in switzerland are you using?

Please also add the adapter version!

I restarted the Meteoalarm instance, used several ones, last where it should have a warning right now region Goldau

**Comment by memberxx** [comment]
I was in contact to Meteoalarm that day, they fixed an issue not sending out Swiss alerts, but I still do not get any alarm.

e.g. Region below is having an alarm right now

 Snow or Ice
Einsiedeln-Wägital


But nothing showing up in the instance/object for this region, seems same for all other Swiss regions I tried, it works fine with all other countries e.g. Germany, Italy

**Comment by jack-blackson** [comment]
Hey! I just checked that, and I think I know where the problem is. Normally, all countries report the alarms via the geocode - these are regions. But there is also the possibility to report it by something like coordinates - and at the moment I am not able to handle that, as I can't map from Geocode to these coordinates. I will have a look at that.

**Comment by memberxx** [comment]
But it worked until when I reported it here. Or was that change to region?

**Comment by locito09** [comment]
Something new?

**Comment by jack-blackson** [comment]
Unfortunatly not. I contacted the meteoalarm team to see what we can do here.

**Comment by memberxx** [comment]
> Unfortunatly not. I contacted the meteoalarm team to see what we can do here. At the moment, I have no clue how to gain the polygon information and parse it with the warnings.

Wondering what changed. Swiss was always using those regions, it was working for some time and just stopped.

**Comment by jack-blackson** [comment]
Quick update, I got the information that countries are switching more and more to polygon data instead of the regions. I think I have a way to handle that, and am already starting to implement it. I hope to have the first test version in the next 2-3 weeks.

**Comment by memberxx** [comment]
Wow sounds great. Thx a lot for your effort

**Comment by locito09** [comment]
Danke für deine arbeit, wenn du möchtest kann ich auch testen

**Comment by memberxx** [comment]
great news, will keep an eye on it once warnings appear. big thank you already

**Comment by memberxx** [comment]
There´s one more thing I quite often recognize. When I change the region it very very often does not update the region and stays same in objects. Not even stop and restart the instance changes anything.

**Comment by memberxx** [comment]
Btw there are some alerts in CH now, but seems it doesn't send any warning e.g. for Muotathal region

https://meteoalarm.org/en/live/warning/977bd6ad-a886-46c5-a1c3-16283b23d579/ffa5383b-84a7-4a9a-9eb3-ce41cd122bb6#list

**Comment by jack-blackson** [comment]
Unfortunately I can not test it today. If you want to give it a try, please install version 3.0.0 via this link (with the GitHub symbol in iobroker“: https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v3.0.0. As a warning, this is an early version, so there could occur problems. Would be happy to hear your feedback

Am 09.02.2024 um 07:12 schrieb memberxx ***@***.***>:



Btw there are some alerts in CH now, but seems it doesn't send any warning e.g. for Muotathal region

https://meteoalarm.org/en/live/warning/977bd6ad-a886-46c5-a1c3-16283b23d579/ffa5383b-84a7-4a9a-9eb3-ce41cd122bb6#list

**Comment by memberxx** [comment]
I loaded the version and added the location via coordinates, but seems it still shows no alert, although meteoalarm shows a yellow alert for the region

Gale force wind

**Comment by jack-blackson** [comment]
Thank you. I think I found the issue - but have to wait again for bad weather, unfortunatly I can just test with live data.

**Comment by memberxx** [comment]
Now there are some

https://meteoalarm.org/en/live/warning/9984a5ad-271a-4834-a0ef-a8a12a4eb089/1308447f-6db4-4803-866e-2d01f453628e#list

**Comment by jack-blackson** [comment]
Hey! Thanks for letting me know. I did some fixes, now it works for me. Can you please give it a try? Just update the version again with the link above.

**Comment by memberxx** [comment]
Do I need to update/reload anything? For me it shows no warning although there is one for the region I put in?

**Comment by memberxx** [comment]
install from URL right?

$ iobroker url https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v3.0.0. --host ioBrokerCUSTOM-copy --debug
install jack-blackson/ioBroker.meteoalarm#v3.0.0.
Installing jack-blackson/ioBroker.meteoalarm#v3.0.0.... (System call)
npm ERR! command git --no-replace-objects checkout v3.0.0.npm ERR! error: pathspec 'v3.0.0.' did not match any file(s) known to git
npm ERR! A complete log of this run can be found in: /opt/iobroker/.npm/_logs/2024-02-19T19_21_18_626Z-debug-0.log
host.ioBrokerCUSTOM-copy Cannot install jack-blackson/ioBroker.meteoalarm#v3.0.0.: 1
ERROR: Process exited with code 25

**Comment by jack-blackson** [comment]
I use "Benutzerdefiniert" - and then with the URL above. 
![image](https://github.com/jack-blackson/ioBroker.meteoalarm/assets/13975634/9175bb90-d9dd-476c-aeb8-38fa9e0965f7)

**Comment by memberxx** [comment]
sorry, copied a . at the end

seems working now, will keep an eye on it for the next time. much appreciated, thx for your work already.

**Comment by jack-blackson** [comment]
Released new version to stable - issue should be solved.
