### ISSUE TITLE
disable english: in Textfield...

### ISSUE THREAD

**Issue by Ilovegym66** [jack-blackson/ioBroker.meteoalarm#27]
Hi, since some days meteoalarm results are in german and! in english! Its not possible to disable the english text at the webpage.

We need a split text object for german and english in the Adapter, because with Alexa it's really crazy the english text to hear.. :-)

**Comment by jack-blackson** [comment]
@Ilovegym66 sorry for the late answer. What country you are using for the alarms?

**Comment by Ilovegym66** [comment]
Germany, i need it only in German, nur the Message are already in both ...

**Comment by jack-blackson** [comment]
I just published V1.0.9 to the latest repository. Please give it a try. If it works out fine, I will update the stable one

**Comment by jack-blackson** [comment]
@Ilovegym66 Seems that they changed the warning and added the english text. I updated the adapter, V1.0.9 was published to the latest repository. Please give it a try and tell me if it works better now - I will then update the stable one.

**Comment by Ilovegym66** [comment]
Works fine now, thank you 👍
