### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by sigi2345** [jack-blackson/ioBroker.meteoalarm#4]
Hallo, es kommt immer dieser Fehler:
`

meteoalarm.0 | 2019-07-19 12:13:55.092 | info | Typename: Hohe Temperaturen
-- | -- | -- | --
meteoalarm.0 | 2019-07-19 12:13:55.092 | info | Type: 5
meteoalarm.0 | 2019-07-19 12:13:50.794 | debug | system.adapter.admin.0: logging true
meteoalarm.0 | 2019-07-19 12:13:50.087 | info | Received data for "Oberösterreich"
meteoalarm.0 | 2019-07-19 12:13:50.025 | info | Requesting data from http://meteoalarm.eu/documents/rss/at/AT007.rss
meteoalarm.0 | 2019-07-19 12:13:50.017 | info | starting. Version 0.3.0 in C:/ioBroker/node_modules/iobroker.meteoalarm, node: v10.16.0
meteoalarm.0 | 2019-07-19 12:13:50.009 | debug | statesDB connected
meteoalarm.0 | 2019-07-19 12:13:50.000 | debug | objectDB connected
meteoalarm.0 | 2019-07-19 12:13:17.472 | error | Error: connect ETIMEDOUT 81.31.132.86:80
meteoalarm.0 | 2019-07-19 12:12:56.465 | info | Requesting data from http://meteoalarm.eu/documents/rss/at/AT007.rss

`

**Comment by jack-blackson** [comment]
I added code to version 0.5, that there is a defined timeout of 10 seconds, and if there is no answer from the website in this time (unfortunately this happed sometimes, it is not really 100% reliable), a proper error message will be added to the log, and a new try will be done after 10 minutes.
