### ISSUE TITLE
Kein Problem aber eine Frage

### ISSUE THREAD

**Issue by nodwan** [jack-blackson/ioBroker.meteoalarm#40]
Hallo, erst mal Dank für Deinen Adapter!

wie stelle ich es an das diese Warnungen mit sayit und sonos ausgegeben werden?

Lieben Dank für Deine Hilfe!

**Comment by jack-blackson** [comment]
Hallo!

Sorry, hab das Issue leider erst jetzt gesehen. Ich vermute du hast schon eine Lösung gefunden, sonst am besten im Forum posten, da kann dir sicher jemand helfen, das funktioniert vermutlich unabhängig vom Adapter.

Schöne Grüße!
