### ISSUE TITLE
Update js-controllers V 3.3.1 Warnmeldungen

### ISSUE THREAD

**Issue by sigi2345** [jack-blackson/ioBroker.meteoalarm#47]
Hallo,

nach einen Update des js-controllers auf V 3.3.1 kommen folgende Warnmeldungen:

`

meteoalarm.0 | 2021-04-30 06:36:01.585 | warn | (14308) State value to set for "meteoalarm.0.tomorrow.type" has wrong type "number" but has to be "string"
-- | -- | -- | --
meteoalarm.0 | 2021-04-30 06:36:01.584 | warn | (14308) State value to set for "meteoalarm.0.tomorrow.level" has wrong type "number" but has to be "string"
meteoalarm.0 | 2021-04-30 06:36:01.583 | warn | (14308) State value to set for "meteoalarm.0.today.type" has wrong type "number" but has to be "string"
meteoalarm.0 | 2021-04-30 06:36:01.583 | warn | (14308) State value to set for "meteoalarm.0.today.level" has wrong type "number" but has to be "string"

`

**Comment by sjfm-design** [comment]
jup, auch hier...

**Comment by jack-blackson** [comment]
Servus!

Sollte mit Version 1.1.5 behoben sein, ist seit wenigen Minuten im Latest.

**Comment by sigi2345** [comment]
Ja, ist weg, kann geschlossen werden.
