### ISSUE TITLE
Supported countries

### ISSUE THREAD

**Issue by Diddeldab** [jack-blackson/ioBroker.meteoalarm#62]
Hello, can you please add Luxembourg to the supported countries ?
Thanks
MBL

**Comment by jack-blackson** [comment]
Hey! I am happy to check that - it is just the problem that I always need to wait for a warning that I can check how the text looks like, if it is added in two languages,.. So if you have one the next time, it would be great if you could download the rss file and post it here.

**Comment by Diddeldab** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
	<channel>
		<atom:link href="http://meteoalarm.eu/documents/rss/lu.rss" rel="self" type="application/rss+xml"/>
		<title>Meteoalarm Luxembourg</title>
		<link>https://www.meteoalarm.eu/fr_FR/0/0/LU.html</link>
		<description>Metoalarm actual warnings from Luxembourg</description>
		<ttl>10</ttl>
		<language>eng</language>
		<item>
			<title>Luxembourg</title>
			<link>https://www.meteoalarm.eu/fr_FR/0/0/LU.html</link>
			<description><![CDATA[<table border="0" cellspacing="0" cellpadding="3"><tr><th colspan="3" align="left">Today</th><td width="28">&nbsp;&nbsp;</td><th colspan="3" align="left">Tomorrow</th></tr><tr><td width="28"><img border="1" src="https://www.meteoalarm.eu/documents/rss/wflag-l2-t3.jpg" alt="awt:3 level:2"></td><td width="28"></td><td width="28"></td><td width="28">&nbsp;&nbsp;</td><td width="28"><img border="1" src="https://www.meteoalarm.eu/documents/rss/wflag-l1-t12.jpg" alt="awt:12 level:1"></td><td width="28"></td><td width="28"></td></tr></table>]]></description>
			<pubDate>Fri, 04 Jun 2021 10:47:27 +0200</pubDate>
			<guid isPermaLink="false">c34671984fe6e635880d145151505812</guid>
		</item>
		<item>
			<title>Luxembourg North</title>
			<link>https://www.meteoalarm.eu/fr_FR/0/0/LU002.html</link>
			<description><![CDATA[<table border="0" cellspacing="0" cellpadding="3"><tr><th colspan="3" align="left">Today</th></tr><tr><td width="28"><img border="1" src="https://www.meteoalarm.eu/documents/rss/wflag-l2-t3.jpg" alt="awt:3 level:2"></td><td><b>From: </b><i>04.06.2021 14:00 CET</i><b> Until: </b><i>04.06.2021 21:59 CET</i></td></tr><tr><td width="28"></td><td>franÃ§ais:  Risque d&#039;orages pouvant localement provoquer des accumulations de prÃ©cipitations entre 15 l/mÂ² et 25 l/mÂ² , de la grÃªle jusqu&#039;Ã  1cm et des rafales de vent de l&#039;ordre de 60 Ã  70 km/h.  
Soyez attentifs
-Si vous pratiquez des activitÃ©s sensibles au risque mÃ©tÃ©orologique ou exposÃ©es aux crues.
-Des phÃ©nomÃ¨nes habituels dans la rÃ©gion mais occasionnellement et localement dangereux sont en effet prÃ©vus.
-Tenez-vous au courant de lâ€™Ã©volution de la situation. 
deutsch:  Risiko fÃ¼r Gewitter mit gebietsweise Niederschlagsmengen zwischen 15 l/mÂ² und 25 l/mÂ²,  Hagel bis zu 1 cm und WindbÃ¶en um 60 - 70 km/h.  
Das Wetter ist potenziell gefÃ¤hrlich. 
-Die vorhergesagten WetterphÃ¤nomene sind nicht wirklich ungewÃ¶hnlich, aber eine erhÃ¶hte Aufmerksamkeit ist bei TÃ¤tigkeiten, die meteorologischen Risiken ausgesetzt sind, angebracht. 
-Halten Sie sich Ã¼ber die zu erwartenden meteorologischen Bedingungen auf dem Laufenden und gehen Sie keine vermeidbaren Risiken ein. 
english:  Risk of thunderstorms that could locally produce accumulations of precipitation between 15 l/mÂ²  and 25 l/mÂ²,  hail up to 1 cm and wind gusts up to 70 km/h.</td></tr><tr><th colspan="3" align="left"><br />Tomorrow</th></tr><tr><td width="28"><img border="1" src="https://www.meteoalarm.eu/documents/rss/wflag-l1-t12.jpg" alt="awt:12 level:1"></td></tr><tr><td width="28"></td><td>No special awareness required</td></tr></table>]]></description>
			<pubDate>Fri, 04 Jun 2021 10:47:27 +0200</pubDate>
			<guid isPermaLink="false">fc5e2882303f5f56478293aeb98a14c8</guid>
		</item>
		<item>
			<title>Luxembourg South</title>
			<link>https://www.meteoalarm.eu/fr_FR/0/0/LU001.html</link>
			<description><![CDATA[<table border="0" cellspacing="0" cellpadding="3"><tr><th colspan="3" align="left">Today</th></tr><tr><td width="28"><img border="1" src="https://www.meteoalarm.eu/documents/rss/wflag-l2-t3.jpg" alt="awt:3 level:2"></td><td><b>From: </b><i>04.06.2021 14:00 CET</i><b> Until: </b><i>04.06.2021 21:59 CET</i></td></tr><tr><td width="28"></td><td>franÃ§ais:  Risque d&#039;orages pouvant localement provoquer des accumulations de prÃ©cipitations entre 15 l/mÂ² et 25 l/mÂ² , de la grÃªle jusqu&#039;Ã  1cm et des rafales de vent de l&#039;ordre de 60 Ã  70 km/h.  
Soyez attentifs
-Si vous pratiquez des activitÃ©s sensibles au risque mÃ©tÃ©orologique ou exposÃ©es aux crues.
-Des phÃ©nomÃ¨nes habituels dans la rÃ©gion mais occasionnellement et localement dangereux sont en effet prÃ©vus.
-Tenez-vous au courant de lâ€™Ã©volution de la situation. 
deutsch:  Risiko fÃ¼r Gewitter mit gebietsweise Niederschlagsmengen zwischen 15 l/mÂ² und 25 l/mÂ²,  Hagel bis zu 1 cm und WindbÃ¶en um 60 - 70 km/h.  
Das Wetter ist potenziell gefÃ¤hrlich. 
-Die vorhergesagten WetterphÃ¤nomene sind nicht wirklich ungewÃ¶hnlich, aber eine erhÃ¶hte Aufmerksamkeit ist bei TÃ¤tigkeiten, die meteorologischen Risiken ausgesetzt sind, angebracht. 
-Halten Sie sich Ã¼ber die zu erwartenden meteorologischen Bedingungen auf dem Laufenden und gehen Sie keine vermeidbaren Risiken ein. 
english:  Risk of thunderstorms that could locally produce accumulations of precipitation between 15 l/mÂ²  and 25 l/mÂ²,  hail up to 1 cm and wind gusts up to 70 km/h.</td></tr><tr><th colspan="3" align="left"><br />Tomorrow</th></tr><tr><td width="28"><img border="1" src="https://www.meteoalarm.eu/documents/rss/wflag-l1-t12.jpg" alt="awt:12 level:1"></td></tr><tr><td width="28"></td><td>No special awareness required</td></tr></table>]]></description>
			<pubDate>Fri, 04 Jun 2021 10:47:27 +0200</pubDate>
			<guid isPermaLink="false">6a05bdf8816ddaf602829f6b619bbe8e</guid>
		</item>
	</channel>
</rss>

**Comment by jack-blackson** [comment]
@Diddeldab Danke - das schaut eigentlich gut aus. Siehst du es auch so, das Französisch hier passen würde? Weil sonst wird der Text sehr lagne, wenn wir Englisch, Deutsch und Französisch einbauen. Oder nur Englisch, damit jeder klar kommt?

**Comment by Diddeldab** [comment]
Hallo, an sich ist die Sprache nicht so wichtig, trotzdem würde ich persönlich vorschlagen Deutsch einzusetzen, die allermeisten (Stamm-) Luxemburger verstehen Deutsch, es sind eher die Hinzugezogenen die es nicht verstehen, wenn man allen gerecht werden wollte würde dreisprachig auch noch nicht ausreichen.... Luxemburg ist halt multinational, wir Luxemburger sind schon fast in der Minderheit....
Im Voraus Vielen Dank für deine Mühe
MfG  Diddeldab

**Comment by jack-blackson** [comment]
@Diddeldab  Ok - ich hab es mal für Deutsch eingebaut. "Leider" gibt es grad keinen Alarm, aber über den Link https://github.com/jack-blackson/ioBroker.countdown/tarball/v1.2.1 kannst du es mal installieren und dann warten wir mal ab, ob es funktioniert bei der nächsten Warnung.

**Comment by Diddeldab** [comment]
Ich habe leider Probleme bei der Installation: Fertig mit Fehler: host.raspberrypi Cannot install jack-blackson/ioBroker.countdown#v1.2.1: 1

**Comment by Diddeldab** [comment]
host.raspberrypi | 2021-06-05 21:17:51.824 | info | Updating repository "default" under "http://download.iobroker.net/sources-dist.json"
-- | -- | -- | --
host.raspberrypi | 2021-06-05 21:17:15.541 | info | iobroker exit 25
host.raspberrypi | 2021-06-05 21:17:14.460 | error | iobroker host.raspberrypi Cannot install jack-blackson/ioBroker.countdown#v1.2.1: 1
host.raspberrypi | 2021-06-05 21:17:14.402 | info | iobroker npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-06-05T19_17_14_381Z-debug.log
host.raspberrypi | 2021-06-05 21:17:14.400 | info | iobroker
host.raspberrypi | 2021-06-05 21:17:14.376 | info | iobroker npm ERR! error: Pfadspezifikation 'v1.2.1' stimmt mit keinen git-bekannten Dateien überein.npm ERR!
host.raspberrypi | 2021-06-05 21:17:14.372 | info | iobroker npm ERR! Command failed: git checkout v1.2.1
host.raspberrypi | 2021-06-05 21:17:14.336 | info | iobroker npm ERR! code 1
host.raspberrypi | 2021-06-05 21:16:40.842 | info | iobroker npm install jack-blackson/ioBroker.countdown#v1.2.1 --loglevel error --prefix "/opt/iobroker" (System call)
host.raspberrypi | 2021-06-05 21:16:40.838 | info | iobroker NPM version: 6.14.12
host.raspberrypi | 2021-06-05 21:16:39.208 | info | iobroker install jack-blackson/ioBroker.countdown#v1.2.1
host.raspberrypi | 2021-06-05 21:16:35.258 | info | iobroker url "https://github.com/jack-blackson/ioBroker.countdown/tarball/v1.2.1"

**Comment by jack-blackson** [comment]
Sorry - heut läufts irgendwie nicht so ganz - das war ein Link für meinen anderen adapter. Der für Meteoalarm ist https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v1.2.1 .

**Comment by Diddeldab** [comment]
Hallo, läuft leider immer noch nicht, erhalte folgenden Fehler:



&nbsp; | &nbsp; | &nbsp; | &nbsp;
-- | -- | -- | --
host.raspberrypi | 2021-06-06 20:27:04.727 | error | instance system.adapter.meteoalarm.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
meteoalarm.0 | 2021-06-06 20:27:04.356 | warn | (1003) Terminated (UNCAUGHT_EXCEPTION): Without reason
meteoalarm.0 | 2021-06-06 20:27:04.353 | info | (1003) terminating
meteoalarm.0 | 2021-06-06 20:27:04.302 | error | (1003) Cannot read property 'indexOf' of undefined
meteoalarm.0 | 2021-06-06 20:27:04.302 | error | (1003) TypeError: Cannot read property 'indexOf' of undefined at parseWeather (/opt/iobroker/node_modules/iobroker.meteoalarm/main.js:330:39) at processJSON (/opt/iobroker/node_modules/iobroke
meteoalarm.0 | 2021-06-06 20:27:04.300 | error | (1003) uncaught exception: Cannot read property 'indexOf' of undefined

**Comment by Diddeldab** [comment]
Sorry, zu früh gebellt, läuft, muss nur noch  auf eine Meldung warten... hatte nicht gemerkt dass man den Norden oder Süden bei Meteoalarm anwählen muss, dachte es wäre automatisch für das ganze Land...

**Comment by jack-blackson** [comment]
Mit Version 2 sollte Luxemburg nun auch wieder dabei sein - ich schließe daher das Issue.
