### ISSUE TITLE
Fix "connectionType" and "dataSource" information

### ISSUE THREAD

**Issue by klein0r** [jack-blackson/ioBroker.meteoalarm#94]
Should be

```
"connectionType": "cloud",
"dataSource": "poll",
```

instead of

https://github.com/jack-blackson/ioBroker.meteoalarm/blob/e9c738be65b5f2a07f9fed2ef6f6260f1fd6d02f/io-package.json#L267-L268

Documentation: https://github.com/ioBroker/ioBroker.repositories/blob/master/README.md#connection-types

**Comment by jack-blackson** [comment]
Will be fixed witn 2.0.8

**Comment by jack-blackson** [comment]
2.0.8 is already in latest ( in the meantime even 2.0.10), and will be moved to stable soon.
