### ISSUE TITLE
Switzerland is missing

### ISSUE THREAD

**Issue by samo6330** [jack-blackson/ioBroker.meteoalarm#95]
Hey there, it would be nice to have Switzerland added to the list of available countries...
Thanks!

**Comment by jack-blackson** [comment]
Hello!

I have good news. It is now possible to also receive the alarms for Switzerland. To install the update, please update the adapter with this link: https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.1.0

I would be happy if you can give me some feedback if it works out fine.
