### ISSUE TITLE
Error: Unexpected close tag

### ISSUE THREAD

**Issue by raschy** [jack-blackson/ioBroker.meteoalarm#99]
meteoalarm 2.0.10
In meinem Logfile finde ich nach jedem Aufruf des Adapters die Meldung "Fehler: Error: Unexpected close tagLine: 0Column: 595Char: >".
Liegt das daran, dass für meine Region gerade 'keine aktuelle Wetterwarnung' vorliegt oder ein genereller Fehler (Änderung bei meteoalarm.org)?

**Comment by sigi2345** [comment]
> meteoalarm 2.0.10 In meinem Logfile finde ich nach jedem Aufruf des Adapters die Meldung "Fehler: Error: Unexpected close tagLine: 0Column: 595Char: >". Liegt das daran, dass für meine Region gerade 'keine aktuelle Wetterwarnung' vorliegt oder ein genereller Fehler (Änderung bei meteoalarm.org)?

Bei mir auch.

**Comment by jack-blackson** [comment]
@raschy Könntest du mir mal das komplette Log schicken, welches mit Meteoalarm zu tun hat? Bitte vorher auf Debug umstellen, und warten, bis es wieder einen Abruf macht, dann sehe ich hoffentlich, wo das Problem entsteht. Super wäre, wenn du mir noch sagst, welche Region du hier abrufst. Ich bekommen den Fehler leider nicht. Sehe auch leider nichts in Sentry. Dachte, da sollten solche Fehler immer gleich auftauchen.

**Comment by raschy** [comment]
Hier ein frisches Debug.Log:
`meteoalarm.0	2022-01-29 19:40:13.362	info	Updated Weather Alarms for Stadt Mönchengladbach -> 0 warning(s) found
meteoalarm.0	2022-01-29 19:40:13.361	debug	12: All Done
meteoalarm.0	2022-01-29 19:40:13.360	debug	11: Set State for Widget
meteoalarm.0	2022-01-29 19:40:13.271	debug	10: Creating HTML Widget
meteoalarm.0	2022-01-29 19:40:13.270	info	Terminated (NO_ERROR): Without reason
meteoalarm.0	2022-01-29 19:40:13.268	debug	Plugin sentry destroyed
meteoalarm.0	2022-01-29 19:40:13.266	error	Fehler: Error: Unexpected close tag Line: 0 Column: 595 Char: >
meteoalarm.0	2022-01-29 19:40:13.258	debug	7: Received Details for URL 1
meteoalarm.0	2022-01-29 19:40:13.088	debug	6: Request Details from URL 1: https://meteoalarm.org?geocode=EMMA_ID:DE114
meteoalarm.0	2022-01-29 19:40:13.087	debug	5.1 Found 1 URLs
meteoalarm.0	2022-01-29 19:40:13.086	debug	5: Processed Atom
meteoalarm.0	2022-01-29 19:40:13.083	debug	4.2: Checked relevance, found 1 relevant alarms
meteoalarm.0	2022-01-29 19:40:13.035	debug	4.1: Warning found: https://meteoalarm.org?geocode=EMMA_ID:DE114 of message type Update
meteoalarm.0	2022-01-29 19:40:12.421	debug	4.1.1: Check Entries
meteoalarm.0	2022-01-29 19:40:12.415	debug	4: Process Atom
meteoalarm.0	2022-01-29 19:40:07.150	debug	3: Received Atom
meteoalarm.0	2022-01-29 19:40:05.516	debug	2: Request Atom from https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-germany
meteoalarm.0	2022-01-29 19:40:05.514	debug	1: Parsed CSV File
meteoalarm.0	2022-01-29 19:40:04.920	debug	0: Delete Alarms
meteoalarm.0	2022-01-29 19:40:04.919	debug	XML Language: de-DE
meteoalarm.0	2022-01-29 19:40:04.917	debug	Setup found: country DE and region DE114 - Stadt Mönchengladbach
meteoalarm.0	2022-01-29 19:40:04.914	debug	Language: de
meteoalarm.0	2022-01-29 19:40:04.808	info	starting. Version 2.0.10 in /opt/iobroker/node_modules/iobroker.meteoalarm, node: v12.22.8, js-controller: 3.3.22
meteoalarm.0	2022-01-29 19:40:04.005	debug	Plugin sentry Initialize Plugin (enabled=true)`

**Comment by raschy** [comment]
Hier ein frisches Debug-Log:
`meteoalarm.0	2022-01-29 19:40:13.362	info	Updated Weather Alarms for Stadt Mönchengladbach -> 0 warning(s) found
meteoalarm.0	2022-01-29 19:40:13.361	debug	12: All Done
meteoalarm.0	2022-01-29 19:40:13.360	debug	11: Set State for Widget
meteoalarm.0	2022-01-29 19:40:13.271	debug	10: Creating HTML Widget
meteoalarm.0	2022-01-29 19:40:13.270	info	Terminated (NO_ERROR): Without reason
meteoalarm.0	2022-01-29 19:40:13.268	debug	Plugin sentry destroyed
meteoalarm.0	2022-01-29 19:40:13.266	error	Fehler: Error: Unexpected close tag Line: 0 Column: 595 Char: >
meteoalarm.0	2022-01-29 19:40:13.258	debug	7: Received Details for URL 1
meteoalarm.0	2022-01-29 19:40:13.088	debug	6: Request Details from URL 1: https://meteoalarm.org?geocode=EMMA_ID:DE114
meteoalarm.0	2022-01-29 19:40:13.087	debug	5.1 Found 1 URLs
meteoalarm.0	2022-01-29 19:40:13.086	debug	5: Processed Atom
meteoalarm.0	2022-01-29 19:40:13.083	debug	4.2: Checked relevance, found 1 relevant alarms
meteoalarm.0	2022-01-29 19:40:13.035	debug	4.1: Warning found: https://meteoalarm.org?geocode=EMMA_ID:DE114 of message type Update
meteoalarm.0	2022-01-29 19:40:12.421	debug	4.1.1: Check Entries
meteoalarm.0	2022-01-29 19:40:12.415	debug	4: Process Atom
meteoalarm.0	2022-01-29 19:40:07.150	debug	3: Received Atom
meteoalarm.0	2022-01-29 19:40:05.516	debug	2: Request Atom from https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-germany
meteoalarm.0	2022-01-29 19:40:05.514	debug	1: Parsed CSV File
meteoalarm.0	2022-01-29 19:40:04.920	debug	0: Delete Alarms
meteoalarm.0	2022-01-29 19:40:04.919	debug	XML Language: de-DE
meteoalarm.0	2022-01-29 19:40:04.917	debug	Setup found: country DE and region DE114 - Stadt Mönchengladbach
meteoalarm.0	2022-01-29 19:40:04.914	debug	Language: de
meteoalarm.0	2022-01-29 19:40:04.808	info	starting. Version 2.0.10 in /opt/iobroker/node_modules/iobroker.meteoalarm, node: v12.22.8, js-controller: 3.3.22
meteoalarm.0	2022-01-29 19:40:04.005	debug	Plugin sentry Initialize Plugin (enabled=true)`

**Comment by vaaarg** [comment]
`<html>
<body>


meteoalarm.1 | 2022-01-29 19:50:08.030 | error | Char: >
-- | -- | -- | --
meteoalarm.1 | 2022-01-29 19:50:08.030 | error | Column: 595
meteoalarm.1 | 2022-01-29 19:50:08.030 | error | Line: 0
meteoalarm.1 | 2022-01-29 19:50:08.030 | error | (10862) Fehler: Error: Unexpected close tag


</body>
</html>`

`<html>
<body>


meteoalarm.0 | 2022-01-29 19:40:06.886 | error | Char: >
-- | -- | -- | --
meteoalarm.0 | 2022-01-29 19:40:06.886 | error | Column: 595
meteoalarm.0 | 2022-01-29 19:40:06.886 | error | Line: 0
meteoalarm.0 | 2022-01-29 19:40:06.886 | error | (10741) Fehler: Error: Unexpected close tag


</body>
</html>`

**Comment by raschy** [comment]
Nachtrag: seit gestern 20:00 liegen für meine Region Warnungen vor. Seit dem tritt der Fehler nicht mehr auf.

**Comment by jack-blackson** [comment]
Ich hab es mir grad angesehen, in Österreich bekomme ich den Fehler nicht, und auch in Hamburg nicht, wo es momentan keine Warnung gibt. Ich werde es mal die nächsten Tage beobachten.

**Comment by jack-blackson** [comment]
@raschy Kommen die Fehler nun bei dir wieder? Soweit ich sehen kann ist für deinen Standort aktuell keine Warnung mehr, und ich bekomme auch keine Fehler.

**Comment by raschy** [comment]
Nachdem am 29.01.2022 mal Warnmeldungen für meinen Standort vorlagen und auch nachdem keine Meldungen mehr vorlagen war der Fehler weg. Würde mal behaupten, 'issue kann geschlossen' werden. Aber dennoch, Danke fürs Kümmerrn.

**Comment by jack-blackson** [comment]
Es könnte sein, das es ein Fehler im XML war, welches wir bekommen haben. @sigi2345  @vaaarg Ist es bei euch nochmal aufgetaucht? Ansonsten schließe ich das Issue vorerst.

**Comment by sigi2345** [comment]
> Es könnte sein, das es ein Fehler im XML war, welches wir bekommen haben. @sigi2345 @vaaarg Ist es bei euch nochmal aufgetaucht? Ansonsten schließe ich das Issue vorerst.

Nein, bei mir nicht
